# This is a config for E2B sandbox template.
# You can use template ID (l3o1mdopphc5t6cqp88v) or template name (opencode-fastest) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("opencode-fastest") # Sync sandbox
# sandbox = await AsyncSandbox.create("opencode-fastest") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('opencode-fastest')

team_id = "4c57653d-986a-4cf1-996e-15076d4d3252"
dockerfile = "e2b.Dockerfile"
template_name = "opencode-fastest"
template_id = "l3o1mdopphc5t6cqp88v"
