name = "fastest-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "fastest-db"
database_id = "local"

[[r2_buckets]]
binding = "BLOBS"
bucket_name = "fastest-blobs"
